question_list = [
    ["___ is the rate of electron flow across a wire.",
    "Voltage", "Current", "Resistance", "Power", "B"],
    ["A ___ is a geometric figure with only 1 dimension.",
    "sphere", "circle", "line", "point", "C"],
    ["According to ___'s First Law, if no force is applied, an object in motion will stay in motion.",
    "Aristotle", "Ohm", "Newton", "Einstein", "C"],
    ["If the two legs of a right triangle are 3 and 4, the hypotenuse of the triangle is ___.",
    "3", "4", "4.5", "5", "D"],
    ["Every robot must be able to SPA, or Sense-Plan-___.",
    "Act", "Alarm", "Aim", "Avoid", "A"],
    ["The two instructors of this robotics course are students at ___.",
    "MIT", "UCB", "CMU", "NYU", "C"],
    ["The two instructors of this robotics course are studying Robotics and ___.",
    "Electrical Engineering", "Industrial Engineering",
    "Mechanical Engineering", "Systems Engineering", "A"],
    ["The code \"for num in range(5): print(num)\" will print:",
    "12345", "1234", "012345", "01234", "C"],
    ["Which of the following is not an energy type?",
    "Kinetic", "Chemical", "Heat", "Gravity", "D"],
    ["Normal force acts against ___ force.",
    "magnetic", "gravitational", "electric", "frictional", "B"],
    ["The code \"print(True and False)\" will print:",
    "True", "False", "True and False", "Nothing will be printed", "B"],
    ["The formula for the area of a circle with radius R is ___.",
    "pi * R", "pi * R^2", "2 * pi * R", "2 * pi * R^2", "B"],
    ["An example of a Python boolean is ___.",
    "10", "0.2", "C", "False", "D"],
    ["Before typing a comment in Python, you need to put the ___ symbol.",
    "#", "//", "\'\'\'", "%", "A"],
    ["The point (3,-5) will be in the ___ quadrant in a graph.",
    "top-right", "top-left", "bottom-right", "bottom-left", "C"],
    ["The point (0,0) in a graph is usually called the ___.",
    "center", "origin", "middle", "endpoint", "B"],
    ["What online software did you use for Lab 1 of this course?",
    "TinkerCAD", "Altium", "CircuitLab", "SystemVision", "A"]
    ]
